development:
  adapter: postgresql
  encoding: unicode
  database: fuckpsql_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: fuckpsql_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: fuckpsql_production
  pool: 5
  username: postgres
  password: